#!/usr/bin/env python3

# Munin — Network Reconnaissance & Threat Analysis Framework
# Copyright (C) 2026 Plinio Lima
# AGPL-3.0 License

"""
auth.py — Authentication middleware for the Munin Flask dashboard.

Features:
  - Login / logout with username + password
  - bcrypt password hashing
  - Flask session management
  - Session timeout (configurable via env)
  - Optional IP allowlist
  - Decorator @login_required for route protection

Environment variables (loaded from .env or shell):
  MUNIN_SECRET_KEY        – Flask secret key (auto-generated by setup.sh)
  MUNIN_DASHBOARD_USER    – Dashboard username (default: admin)
  MUNIN_DASHBOARD_PASS    – Dashboard password (default: changeme)
  MUNIN_SESSION_TIMEOUT   – Session timeout in seconds (default: 3600)
  MUNIN_IP_ALLOWLIST      – Comma-separated IPs allowed (empty = all)
"""

from __future__ import annotations

import os
import time
import hashlib
import logging
from functools import wraps
from typing import Optional

logger = logging.getLogger("munin.auth")

# ─────────────────────────────────────────────────────────────────────────────
# Configuration (read from environment)
# ─────────────────────────────────────────────────────────────────────────────

def _load_env() -> None:
    """Load .env if python-dotenv is available."""
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass


_load_env()

DASHBOARD_USER    = os.environ.get("MUNIN_DASHBOARD_USER", "admin")
DASHBOARD_PASS    = os.environ.get("MUNIN_DASHBOARD_PASS", "changeme")
SESSION_TIMEOUT   = int(os.environ.get("MUNIN_SESSION_TIMEOUT", "3600"))
IP_ALLOWLIST_RAW  = os.environ.get("MUNIN_IP_ALLOWLIST", "")

IP_ALLOWLIST: list[str] = [
    ip.strip() for ip in IP_ALLOWLIST_RAW.split(",") if ip.strip()
]

# ─────────────────────────────────────────────────────────────────────────────
# Password handling (bcrypt with sha256 fallback)
# ─────────────────────────────────────────────────────────────────────────────

def _hash_password(password: str) -> str:
    """Return a bcrypt hash of the password (or sha256 fallback)."""
    try:
        import bcrypt
        return bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
    except ImportError:
        logger.warning("bcrypt not installed — using SHA-256 fallback (install bcrypt for production)")
        return "sha256:" + hashlib.sha256(password.encode()).hexdigest()


def _check_password(password: str, hashed: str) -> bool:
    """Verify password against a stored hash."""
    if hashed.startswith("sha256:"):
        return ("sha256:" + hashlib.sha256(password.encode()).hexdigest()) == hashed
    try:
        import bcrypt
        return bcrypt.checkpw(password.encode(), hashed.encode())
    except ImportError:
        return False


# Pre-hash the configured password at startup
_PASS_HASH = _hash_password(DASHBOARD_PASS)


def verify_credentials(username: str, password: str) -> bool:
    """Return True if username and password are valid."""
    if username != DASHBOARD_USER:
        return False
    return _check_password(password, _PASS_HASH)


# ─────────────────────────────────────────────────────────────────────────────
# Flask integration
# ─────────────────────────────────────────────────────────────────────────────

def init_auth(app) -> None:
    """
    Configure Flask app for authentication.
    Call this once before app.run().

    Sets:
      - app.secret_key from MUNIN_SECRET_KEY env var
      - SESSION_COOKIE_HTTPONLY, SESSION_COOKIE_SAMESITE
    """
    secret = os.environ.get("MUNIN_SECRET_KEY")
    if not secret:
        import secrets
        secret = secrets.token_hex(32)
        logger.warning("MUNIN_SECRET_KEY not set — using a random key (sessions will reset on restart)")

    app.secret_key = secret
    app.config["SESSION_COOKIE_HTTPONLY"] = True
    app.config["SESSION_COOKIE_SAMESITE"] = "Lax"
    app.config["PERMANENT_SESSION_LIFETIME"] = SESSION_TIMEOUT

    logger.info(
        f"Auth: user='{DASHBOARD_USER}'  timeout={SESSION_TIMEOUT}s  "
        f"ip_allowlist={IP_ALLOWLIST or 'all'}"
    )


def is_authenticated(session) -> bool:
    """Return True if the current session is valid and not expired."""
    if not session.get("authenticated"):
        return False
    last_activity = session.get("last_activity", 0)
    if time.time() - last_activity > SESSION_TIMEOUT:
        session.clear()
        return False
    return True


def login_session(session, username: str) -> None:
    """Mark the session as authenticated."""
    session["authenticated"] = True
    session["username"]      = username
    session["last_activity"] = time.time()
    session.permanent        = True


def logout_session(session) -> None:
    """Clear the session."""
    session.clear()


def check_ip_allowlist(remote_addr: str) -> bool:
    """Return True if the IP is allowed (or if the allowlist is empty)."""
    if not IP_ALLOWLIST:
        return True
    return remote_addr in IP_ALLOWLIST


def login_required(f):
    """
    Flask route decorator — redirects to /login if not authenticated.

    Usage:
        @app.route("/")
        @login_required
        def index():
            ...
    """
    @wraps(f)
    def decorated(*args, **kwargs):
        from flask import session, redirect, url_for, request, abort

        # IP allowlist check
        if not check_ip_allowlist(request.remote_addr):
            logger.warning(f"Auth: blocked request from {request.remote_addr}")
            abort(403)

        if not is_authenticated(session):
            return redirect(url_for("login", next=request.url))

        # Refresh last_activity on each request
        session["last_activity"] = time.time()
        return f(*args, **kwargs)

    return decorated


# ─────────────────────────────────────────────────────────────────────────────
# Login page HTML
# ─────────────────────────────────────────────────────────────────────────────

LOGIN_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Munin · Login</title>
  <style>
    :root {
      --bg: #0a0d12; --surface: #111620; --border: #1e2a3a;
      --accent: #3b82f6; --text: #e2e8f0; --muted: #64748b;
      --crit: #ef4444; --radius: 10px;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: var(--bg); color: var(--text);
      font-family: 'Inter', system-ui, sans-serif;
      min-height: 100vh;
      display: flex; align-items: center; justify-content: center;
    }
    .login-box {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 2.5rem 2rem;
      width: 100%; max-width: 380px;
    }
    .logo {
      display: flex; align-items: center; gap: .7rem;
      margin-bottom: 2rem;
    }
    .logo-icon {
      width: 40px; height: 40px; color: #60a5fa;
    }
    .logo-text { font-size: 22px; font-weight: 600; }
    .logo-sub { font-size: 11px; color: var(--muted); margin-top: 2px; }
    label { display: block; font-size: 12px; color: var(--muted);
            text-transform: uppercase; letter-spacing: .06em; margin-bottom: .4rem; }
    input {
      width: 100%; padding: .65rem .9rem;
      background: var(--bg); border: 1px solid var(--border);
      border-radius: 6px; color: var(--text); font-size: 14px;
      margin-bottom: 1.2rem; outline: none;
      transition: border-color .15s;
    }
    input:focus { border-color: var(--accent); }
    .btn {
      width: 100%; padding: .75rem;
      background: var(--accent); border: none;
      border-radius: 6px; color: #fff;
      font-size: 14px; font-weight: 600;
      cursor: pointer; transition: opacity .15s;
    }
    .btn:hover { opacity: .85; }
    .error {
      background: rgba(239,68,68,.12);
      border: 1px solid rgba(239,68,68,.3);
      border-radius: 6px; padding: .6rem .9rem;
      font-size: 13px; color: var(--crit);
      margin-bottom: 1rem;
    }
    .footer { margin-top: 1.5rem; font-size: 11px; color: var(--muted); text-align: center; }
  </style>
</head>
<body>
  <div class="login-box">
    <div class="logo">
      <svg class="logo-icon" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
        <path d="M100 15 C75 15 55 30 50 55 C45 75 52 88 45 100 C38 112 20 115 18 130
                 C16 145 28 158 42 162 C35 170 30 178 35 185 C40 192 55 190 65 183
                 C72 178 80 172 90 170 C95 180 98 190 105 193 C112 196 118 188 115 178
                 C122 182 130 185 136 180 C142 175 140 165 134 160
                 C148 155 160 142 158 128 C156 114 142 108 140 95
                 C138 82 145 70 142 55 C138 35 120 15 100 15Z
                 M85 65 C88 62 93 63 95 67 C97 71 94 75 90 74 C86 73 83 68 85 65Z"/>
      </svg>
      <div>
        <div class="logo-text">Munin</div>
        <div class="logo-sub">Cyber Risk Intelligence Platform</div>
      </div>
    </div>

    {% if error %}
    <div class="error">{{ error }}</div>
    {% endif %}

    <form method="POST" action="/login">
      <input type="hidden" name="next" value="{{ next }}">
      <div>
        <label>Username</label>
        <input type="text" name="username" autocomplete="username"
               placeholder="admin" required autofocus>
      </div>
      <div>
        <label>Password</label>
        <input type="password" name="password" autocomplete="current-password"
               placeholder="••••••••" required>
      </div>
      <button class="btn" type="submit">Sign in</button>
    </form>

    <div class="footer">Munin v2 · Use only on authorised networks</div>
  </div>
</body>
</html>"""
